"""profile_singleton_guard

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-14 00:04:48.391320
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("is_singleton", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.create_unique_constraint("uq_profiles_singleton", "profiles", ["is_singleton"])
    op.create_check_constraint("ck_profiles_singleton", "profiles", "is_singleton = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_profiles_singleton", "profiles", type_="check")
    op.drop_constraint("uq_profiles_singleton", "profiles", type_="unique")
    op.drop_column("profiles", "is_singleton")
    # ### end Alembic commands ###
